[package]

name = "todo-backend-rustful"
version = "0.0.2"
authors = ["Rodolphe PELLOUX-PRAYER <rodolphe@damsy.net>"]

[[bin]]
name = "todo"

[dependencies]
rustful = "0.5"
rustc-serialize = "0.3"
unicase = "1.0"
